apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hami-dra-driver.fullname" . }}-clusterrole-binding
  labels:
    {{- include "hami-dra-driver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hami-dra-driver.fullname" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "hami-dra-driver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
