apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hami-dra-driver.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hami-dra-driver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hami-dra-driver.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "hami-dra-driver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
