blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/kubernetes-sigs/dra-driver-test-stub/discussions
    about: Ask a question about the project or how to use it.
